version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - /usr/src/api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - sqs

  tenantreader:
    build:
      context: ./tenantreader
      dockerfile: Dockerfile
    volumes:
      - /usr/src/tenantreader
    depends_on:
      - sqs

  provisioning:
    build:
      context: ./provisioning
      dockerfile: Dockerfile
    volumes:
      - /usr/src/provisioning
    depends_on:
      - sqs

  scanner:
    build:
      context: ./scanner
      dockerfile: Dockerfile
    volumes:
      - /usr/src/scanner
    depends_on:
      - sqs

  sqs:
    image: s12v/elasticmq
    ports:
    - "9324:9324"
    volumes:
    - ./config/elasticmq.conf:/etc/elasticmq/elasticmq.conf
